# DUTCHED's ALT MANAGER

owner:
# Syntax: - 443762652259418132 (Discord ID), there can be multiple owners
  - 443762652259418132

discord:
# Bot token can be found where you created your bot
  botToken: ""
  prefix: "!"

format:
# Customize your embeds
  successTitle: "Success!"
  errorTitle: "Error!"
  footer: "Dutched's Alt Manager v1.2.1"
  embedColor: "#9702ed"

minecraft:
# Pick either mojang/microsoft (make sure its lowercased!)
  auth: "mojang"
  serverIP: "play.crystaldev.co"
  serverPort: "25565"
  version: "1.8.9"
  joinCommand: "/ruby"
  joinDelay: 3 # Time in between alts joining (in seconds)
  hideErrors: false # To hide the "unknown transaction" warning, if you have trouble getting the bots up you might want to change this to false

alts:
# Example: - AltEmail@email.com:Password123!
- AltEmail@email.com:Password123!
